version: '3'
services:
  front-end:
    container_name: frontend-todolist
    build:
      context: './'
      dockerfile: ./docker/front-end.dockerfile
    volumes:
      - ./:/app
    expose:
      - '8080'
    ports:
      - '8080:8080'
    networks:
      - mysql-ntw
  
networks:
  mysql-ntw:
    external: true